# Generated by Django 5.1.3 on 2024-11-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyTokens',
            new_name='SpotifyToken',
        ),
    ]
